
export const goods = {
  DELETE_BY_ID: 'DELETE_BY_ID',
  SAVE_BY_ID: 'SAVE_BY_ID',
  CREATE_GOOD: 'CREATE_GOOD',
  FETCH_GOODS_START: 'FETCH_GOODS_START',
  FETCH_GOODS_SUCCESS: 'FETCH_GOODS_SUCCESS',
  FETCH_GOODS_BY_CATEGORIES: 'FETCH_GOODS_BY_CATEGORIES',
}

export const categories = {
  FETCH_CATEGORIES_START: 'FETCH_CATEGORIES_START',
  FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
}
